name: Update Readme File test
on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:
jobs:
  update-lastfm:
    name: Update Music Stats
    runs-on: ubuntu-latest
    steps:
      # 1. ç°½å‡ºä»£ç¢¼
      - uses: actions/checkout@v3

      # 2. æ›´æ–° Last.fm çµ±è¨ˆæ•¸æ“š
      - name: Update Last.fm README
        uses: dxnter/lastfm-readme@v1.6.0
        with:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_USER: GhostMxv
          SHOW_TITLE: false
          LOCALE: en-US

      # 3. åŸ·è¡Œ sed æ›¿æ›
      - name: Remove blockquote from README
        run: |
          sed -i 's/> ğŸ¶/-/g' README.md
          sed -i 's/> âˆ™/-/g' README.md

      # 4. è‡ªå‹•æäº¤æ›´æ”¹
      - name: Commit Last.fm changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "docs(readme): update last.fm stats"
          commit_user_name: "README Bot"
          commit_user_email: "bot@example.com"

  update-feed:
    needs: update-lastfm
    runs-on: ubuntu-latest
    steps:
      # 1. ç°½å‡ºä»£ç¢¼
      - uses: actions/checkout@v5

      # 2. æ›´æ–° Blog Feed
      - uses: sarisia/actions-readme-feed@v1
        id: feed
        with:
          file: 'README.md'
          max_entry: 6
          format: '- ${monthshort} ${day} ${year} - [${title}](${url})'
          timezone: 'Asia/Hong_Kong'
          url: |
            https://gholts.top/rss.xml

      # 3. è‡ªå‹•æäº¤æ›´æ”¹
      - name: Commit feed changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "docs(readme): update blog feed"
          commit_user_name: "README Bot"
          commit_user_email: "bot@example.com"
